remote_theme: pmarsceill/just-the-docs

title: "SQLite ICU MinGW"

# Google Analytics Tracking (optional)
google_analytics: UA-197722197-1
ga_tracking: UA-197722197-1

# Plugins
plugins:
  - jekyll-seo-tag
