remote_theme: pmarsceill/just-the-docs

title: "SQLite ICU MinGW"

# Google Analytics Tracking
google_analytics: UA-197722197-1
ga_tracking: UA-197722197-1

webmaster_verifications:
  google: "eeyANkR7sUrPKHD5z5GheWmEg9GY5Sjpn1aCSpbx0J0"
  yandex: "8703f875cde8e0ac"

# Plugins
plugins:
  - jekyll-seo-tag
