@echo off

set Path=G:\ProgramsMisc\Anaconda\msys2\mingw32\bin;%Path%
set SRC_DIR=.\src
set INC_DIR=.\include
set BIN_DIR=.\bin
set LIBS=-lpthread -ldl -lm
set SOURCES="%SRC_DIR%\shell.c" "%SRC_DIR%\sqlite3.c" "%SRC_DIR%\test_sqllog.c"

rem Get ICU compile options
set CLI=pkg-config --cflags --libs --static icu-i18n
for /f "usebackq delims=" %%i in (`%CLI%`) do (set ICU_OPTIONS=%%i)

set FEATURES=^
-DSQLITE_DQS=0 ^
-DSQLITE_LIKE_DOESNT_MATCH_BLOBS ^
-DSQLITE_MAX_EXPR_DEPTH=0 ^
-DSQLITE_OMIT_DEPRECATED ^
-DSQLITE_DEFAULT_FOREIGN_KEYS=1 ^
-DSQLITE_DEFAULT_SYNCHRONOUS=1 ^
-DSQLITE_ENABLE_COLUMN_METADATA ^
-DSQLITE_ENABLE_DBPAGE_VTAB ^
-DSQLITE_ENABLE_DBSTAT_VTAB ^
-DSQLITE_ENABLE_EXPLAIN_COMMENTS ^
-DSQLITE_ENABLE_FTS3 ^
-DSQLITE_ENABLE_FTS3_PARENTHESIS ^
-DSQLITE_ENABLE_FTS3_TOKENIZER ^
-DSQLITE_ENABLE_FTS4 ^
-DSQLITE_ENABLE_FTS5 ^
-DSQLITE_ENABLE_GEOPOLY ^
-DSQLITE_ENABLE_MATH_FUNCTIONS ^
-DSQLITE_ENABLE_JSON1 ^
-DSQLITE_ENABLE_QPSG ^
-DSQLITE_ENABLE_RBU ^
-DSQLITE_ENABLE_ICU ^
-DSQLITE_ENABLE_RTREE ^
-DSQLITE_ENABLE_STMTVTAB ^
-DSQLITE_ENABLE_STAT4 ^
-DSQLITE_ENABLE_SQLLOG ^
-DSQLITE_SOUNDEX


gcc -I"%INC_DIR%" ^
  %SOURCES% ^
  %LIBS% ^
  %ICU_OPTIONS% ^
  %FEATURES% ^
  -o %BIN_DIR%\sqlite3.exe

