#!/usr/make
#
#

SQLITE3_DIR := $(abspath $(lastword $(MAKEFILE_LIST)))
SQLITE3_DIR := $(patsubst %/,%,$(dir $(SQLITE3_DIR)))/sqlite3
SQLITE3_BLD := $(SQLITE3_DIR)/build
SQLITE3_INC := $(SQLITE3_BLD)
SQLITE3_SRC := $(SQLITE3_BLD)

CFLAGS_EXTRAS :=
LIBS :=
DEFAULT_LIBS := -lpthread -lm -ldl
LIBOPTS := -static-libgcc -static-libstdc++
LIBS += $(LIBOPTS)

ICU_CFLAGS := $(shell icu-config --cflags --cppflags)
export CFLAGS_EXTRAS += $(ICU_CFLAGS)
ICU_LDFLAGS := $(shell icu-config --ldflags --ldflags-system)
export LIBS += $(ICU_LDFLAGS) $(filter-out $(ICU_LDFLAGS),$(DEFAULT_LIBS))

FEATURES := \
  -D_HAVE_SQLITE_CONFIG_H \
  -DSQLITE_DQS=0 \
  -DSQLITE_LIKE_DOESNT_MATCH_BLOBS \
  -DSQLITE_MAX_EXPR_DEPTH=0 \
  -DSQLITE_OMIT_DEPRECATED \
  -DSQLITE_DEFAULT_FOREIGN_KEYS=1 \
  -DSQLITE_DEFAULT_SYNCHRONOUS=1 \
  -DSQLITE_ENABLE_COLUMN_METADATA \
  -DSQLITE_ENABLE_DBPAGE_VTAB \
  -DSQLITE_ENABLE_DBSTAT_VTAB \
  -DSQLITE_ENABLE_EXPLAIN_COMMENTS \
  -DSQLITE_ENABLE_FTS3 \
  -DSQLITE_ENABLE_FTS3_PARENTHESIS \
  -DSQLITE_ENABLE_FTS3_TOKENIZER \
  -DSQLITE_ENABLE_FTS4 \
  -DSQLITE_ENABLE_FTS5 \
  -DSQLITE_ENABLE_GEOPOLY \
  -DSQLITE_ENABLE_MATH_FUNCTIONS \
  -DSQLITE_ENABLE_JSON1 \
  -DSQLITE_ENABLE_QPSG \
  -DSQLITE_ENABLE_RBU \
  -DSQLITE_ENABLE_ICU \
  -DSQLITE_ENABLE_RTREE \
  -DSQLITE_ENABLE_STMTVTAB \
  -DSQLITE_ENABLE_STAT4 \
  -DSQLITE_SOUNDEX \
  -DNDEBUG

export OPT_FEATURE_FLAGS := $(FEATURES)

#
###############################################################################
all: 
	$(MAKE) all dll
